version: '3.7'
services:
  renterd:
    image: ghcr.io/siafoundation/renterd:master
    env_file:
      - .env
    ports:
      - 9887:9980
      - 9888:8080
      - 9889:9981
    volumes:
      - ./data:/data
    restart: unless-stopped
    stop_grace_period: 5m